version: '3.8'

services:
  runner:
    image: github-actions-runner:latest
    container_name: github-runner
    environment:
      - REPO_URL=https://github.com/huynhhoang04/quickbite-runner
      - RUNNER_TOKEN=BXMV5CEIZI3HQ3JCTHS7L43KTAO6A
      - RUNNER_NAME=quickbite-runner
      - RUNNER_WORKDIR=/tmp/runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/tmp/runner
    restart: unless-stopped
    network_mode: host

volumes:
  runner-data: